exclude: (^docs/_build/)|(^.notebooks/)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-ast
    - id: check-toml
    - id: debug-statements
    - id: no-commit-to-branch
      args: ['--branch', 'main']
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "0.9.0"
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/econchick/interrogate
    rev: 1.4.0
    hooks:
      - id: interrogate
        args: [--quiet, --fail-under=70, .]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.0.245'
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.990
    hooks:
    - id: mypy
      args: [--ignore-missing-imports]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
