site_name: '{{cookiecutter.package_name}}'
repo_url: {{cookiecutter.repository}}

nav:
  - Home: index.md
  - Usage: usage.ipynb
  - API: {{cookiecutter.__package_slug}}.md
  - Changelog: changelog.md
  - Contributing: contributing.md
  - Conduct: conduct.md

theme:
  name: "material"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
- search
- mkdocstrings
- include-markdown
- mkdocs-jupyter
