site_name: '{{cookiecutter.package_name}}'
repo_url: {{cookiecutter.repository}}

nav:
  - Home: index.md
  - Usage: usage.ipynb
  - Changelog: changelog.md
  - Contributing: contributing.md
  - Conduct: conduct.md

theme:
  name: "material"

plugins:
- search
- mkdocstrings:
    enabled: true
    custom_templates: templates
    default_handler: python
    handlers:
      python:
        options:
          show_source: false
- include-markdown
- mkdocs-jupyter
