site_name: '{{cookiecutter.package_name}}'
repo_url: {{cookiecutter.repository}}

nav:
  - Home: index.md
  - Usage: usage.ipynb
  - API: {{cookiecutter.__package_slug}}.md
  - Changelog: changelog.md
  - Contributing: contributing.md
  - Conduct: conduct.md

theme:
  name: "material"

plugins:
- search
- mkdocstrings
- include-markdown
- mkdocs-jupyter
